name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: NghiaTran0502/NghiaTran0502@master
        with:
          WAKATIME_API_KEY: 9894fef3-b2c8-4c2b-8ada-5cf8210072a3
          GH_TOKEN: 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
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
